version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: airflow-postgres
    restart: always
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  airflow:
    image: apache/airflow:latest
    container_name: airflow
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth

    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags  
      - ~/.aws:/home/airflow/.aws:ro
    command: ["webserver"]  